services:
  - type: web
    name: langbuddy
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: SF_API_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_USERNAME
        value: admin
